name: tag-releaser

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
      GOPRIVATE: "github.com/publicit/*"
      GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      AWS_DEFAULT_REGION: us-east-2
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.DEV_GOOGLE_CLIENT_ID }}
      REACT_APP_BASE_API_URL: "/api"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Build, and push files to AWS S3
        run: |
          # export REACT_APP_TAG_NAME="${GITHUB_REF_NAME}"
          # export REACT_APP_GIT_COMMIT=$(git rev-parse HEAD)
          ./scripts/check-aws.sh
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/g4i9j9d8
          make docker-build
          docker tag ui:latest public.ecr.aws/g4i9j9d8/ui:latest
          docker push public.ecr.aws/g4i9j9d8/ui:latest