name: node-builder

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install deps
        run: |
          npm ci
      - name: Build
        run: |
          npm run build
      - name: Linter
        run: |
          npm run lint
      - name: Prettier
        run: |
          npm run format:check
