name: tag-releaser

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: false
      CGO_ENABLED: 0
      GOPRIVATE: "github.com/publicit/*"
      GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      AWS_DEFAULT_REGION: us-east-2
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.DEV_GOOGLE_CLIENT_ID }}
      REACT_APP_BASE_API_URL: "/api"
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
        with:
          node-version: 18.x
      - name: Build, and sync files with S3 bucket
        run: |
          export REACT_APP_TAG_NAME="${GITHUB_REF_NAME}"
          export REACT_APP_GIT_COMMIT="${GITHUB_SHA}"
          npm i
          npm run build
          ./scripts/check-aws.sh
          aws s3 sync ./build/ s3://dev.ui.publicit.com --delete