name: tag-releaser

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
      GOPRIVATE: "github.com/publicit/*"
      GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      AWS_DEFAULT_REGION: us-east-2
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REACT_APP_TAG_NAME: ${GITHUB_REF_NAME}
      REACT_APP_KEYCLOAK_REALM: publicit
      REACT_APP_KEYCLOAK_URL: "https://dev.sso.publicitux.com/"
      REACT_APP_KEYCLOAK_CLIENT_ID: "publicit-react-auth"
      REACT_APP_BASE_API_URL: "/api"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Build, and push files to AWS S3
        run: |
          npm i
          npm run build
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install
          aws s3 sync ./build/ s3://dev.ui.publicit.com --delete
